README.md
Works on https://app.clickup.com/t/26uuayb
=> Show multiple pairs in README example

README.md, package.json, src/data/d2-program-rules/D2ProgramRules.ts, src/data/d2-program-rules/D2ProgramRules.types.ts, src/domain/repositories/ProgramsRepository.ts, src/scripts/commands/programs.ts, src/scripts/postinstall.sh, src/utils/log.ts, yarn.lock
Closes https://app.clickup.com/t/28ec4rq
This PR will contain all the modifications required by the feedback we get from the client: https://app.clickup.com/t/2ad8fu9
=> Run program rules (fixes+refactors)

src/data/MetadataD2Repository.ts, src/scripts/commands/translations.ts
=> [fix] translations script

src/data/ProgramsD2Repository.ts, src/domain/usecases/ExportProgramsUseCase.ts, src/scripts/commands/programs.ts
Required by https://app.clickup.com/t/3bvwg8r
* Export: add `--orgunits-ids` option.
* Imports: chunked payloads, better error handling, JSON error generation.
* Add more logging.
=> [programs] Refine import/export

src/data/RecipientD2Repository.ts, src/domain/entities/Notification.ts, src/domain/repositories/RecipientRepository.ts, src/domain/usecases/GetDanglingValuesUseCase.ts, src/scripts/commands/dataValues.ts
Required by https://app.clickup.com/t/865bnt2ta
Example: `--notify=cZrjO64Znrf,DPS7dhwYrjR,user@server.org`
=> dataValues --notify option accepts email or user/userGroup IDs

src/data/ProgramEventsD2Repository.ts, src/domain/entities/ProgramEvent.ts, src/domain/usecases/DeleteProgramDataValuesUseCase.ts, src/scripts/commands/programs.ts
=> Add command to delete program events

README.md, src/data/NotificationsEmailRepository.ts, src/data/UserD2Repository.ts, src/domain/entities/Notification.ts, src/domain/entities/Stats.ts, src/domain/entities/User.ts, src/domain/entities/UserMigrateStatus.ts, src/domain/repositories/UserRepository.ts, src/domain/usecases/MigrateUserNameUseCase.ts, src/scripts/cli.ts, src/scripts/commands/users.ts
-   **Issue:** [https://app.clickup.com/t/86780pd0t](https://app.clickup.com/t/86780pd0t)
Migrate email to username
```bash
$ yarn start users migrate \
--url='http://USER:PASSWORD@HOST:PORT' \
--from='email' \
--to='username' \
--post
```
Migrate username and sending an email to the user
```bash
yarn start users migrate \
--url='http://USER:PASSWORD@HOST:PORT' \
--send-notification \
--from='email' \
--to='username' \
--template-path='email.json' \
--post
```
Migrate username and sending an email to the user and the administrator
```bash
yarn start users migrate \
--url='http://USER:PASSWORD@HOST:PORT' \
--admin-email="admin@example.com" \
--send-notification \
--from='email' \
--to='username' \
--template-path='email.json' \
--post
```
**email.json** must have the following structure: …
=> Update user and send email

src/data/ImportTranslationsRepositorySpreadsheetRepository.ts
- When a sheet starts with !, it's skipped.
- Add some docs to the repository.
=> Skip sheets starting with exclamation + add docs

src/domain/repositories/SpreadsheetXlsxRepository.ts
Required by https://app.clickup.com/t/865cru999
=> [fix ]Add support for cell type number

README.md, src/data/DataSetExecutionD2Repository.ts, src/data/DataSetExecutionJsonRepository.ts, src/data/DataSetsD2Repository.ts, src/data/DataValuesD2Repository.ts, src/data/OrgUnitD2Repository.ts, src/data/SettingsD2Repository.ts, src/data/SettingsJsonRepository.ts, src/data/UserD2Repository.ts, src/domain/entities/Base.ts, src/domain/entities/DataSet.ts, src/domain/entities/OrgUnit.ts, src/domain/entities/Settings.ts, src/domain/repositories/DataSetExecutionRepository.ts, src/domain/repositories/DataSetsRepository.ts, src/domain/repositories/DataValuesRepository.ts, src/domain/repositories/OrgUnitRepository.ts, src/domain/repositories/SettingsRepository.ts, src/domain/repositories/UserRepository.ts, src/domain/usecases/SendNotificationDataValuesUseCase.ts, src/scripts/commands/dataValues.ts
-   **Issue:** Closes https://app.clickup.com/t/865cpwt3a
Email example:
d2-docker: [docker.eyeseetea.com/eyeseetea/dhis2-data:2.38-widp-dev](docker.eyeseetea.com/eyeseetea/dhis2-data:2.38-widp-dev)
Script can be executed using json or dhis datastore as storage:
```
yarn start datavalues monitoring-values \
--url='http://USER:PASSWORD@localhost:8080' \
--storage=json \
--settings-path=./settings.json \
--executions-path=./executions.json \
--email-path-template=./email.json \
--send-email-after-minutes=5
```
you can download an example of each json file in the clickup issue. 
For the following script you must create a `d2-notifications` namespace with a key **settings**. Put the content of the **settings.json** file from clickup in there and save it.
```
yarn start datavalues …
```
=> Monitor data values and send email

src/domain/usecases/SendNotificationDataValuesUseCase.ts
-   **Issue:** Closes https://app.clickup.com/t/865cpwt3a
Unique emails for each user
=> fix: send email to each user in the group

src/domain/entities/Settings.ts, src/domain/usecases/SendNotificationDataValuesUseCase.ts
-   **Issue:** Closes https://app.clickup.com/t/865cpwt3a
=> change user groups key from usersGroups to userGroups

README.md, src/data/DataSetExecutionJsonRepository.ts, src/data/DataSetsD2Repository.ts, src/data/DataValuesD2Repository.ts, src/data/ExecutionD2Repository.ts, src/data/SettingsD2Repository.ts, src/data/TimeZoneD2Repository.ts, src/data/UserD2Repository.ts, src/domain/entities/DataSet.ts, src/domain/entities/Settings.ts, src/domain/entities/User.ts, src/domain/repositories/DataSetExecutionRepository.ts, src/domain/repositories/DataValuesRepository.ts, src/domain/repositories/ExecutionRepository.ts, src/domain/repositories/UserRepository.ts, src/domain/usecases/SendNotificationDataValuesUseCase.ts, src/scripts/commands/dataValues.ts
-   **Issue:** Closes https://app.clickup.com/t/865d2km2d
Email example:
Script is pretty much the same, only difference is that now we have 2 email templates (dataSets and dataElements), you can download an example in the issue.
```
LOG_LEVEL=debug yarn start datavalues monitoring-values \
--url='http://user:password@localhost:8080' \
--storage=datastore \
--settings-path=d2-reports.monitoring \
--executions-path=d2-reports.executions \
--email-ds-path-template=./email-ds.json \
--email-de-path-template=./email-de.json \
--send-email-after-minutes=1
```
=> Notify data value changes for specific data elements

README.md, package.json, src/data/LoadingPlanHarRepository.ts, src/domain/entities/LoadingPlan.ts, src/domain/repositories/LoadingPlanRepository.ts, src/domain/usecases/RunLoadingPlanUseCase.ts, src/scripts/cli.ts, src/scripts/commands/loadTesting.ts, yarn.lock
Required by https://app.clickup.com/t/8678ut5d0
```shell
npx ts-node src/index.ts \
loadTesting run \
--plans-json ocg-plans.json \
--hars-folder="." \ # Folder of the HAR files
--har-url="https://dhis2.ocg.msf.org" \ # Where the HAR was recorded
--base-url="https://dhis2-test-elca.ocg.msf.org" \ # Where the loading test should be executed
--auth='load-test-est:PASSWORD' \
all2
```
Example ocg-plans.json:
```json
[
{
"id": "all2",
"executions": [
{ "windowTimeSecs": 60, "users": 1 },
{ "windowTimeSecs": 60, "users": 5 }
],
"name": "all.har"
}
]
```
=> Test loading scenarios

src/data/d2-program-rules/D2ProgramRules.ts, yarn.lock
The tei-id argument was defined in the script but not used in the repo. Fixed.
`programs run-program-rules --tei-id=BdISu6MJt2`
=> [fix ] Pass tei ids argument

package.json, src/data/ProgramEventsD2Repository.ts, src/data/d2-program-rules/D2ProgramRules.ts, src/domain/repositories/ProgramsRepository.ts, src/scripts/commands/programs.ts, src/scripts/common.ts, yarn.lock
Required by https://app.clickup.com/t/862kgxu0b
Uses https://github.com/EyeSeeTea/d2-api/pull/139
Generic:
- Update to latest d2-api with type-fields for events
- Use standard environment variable to use proxy agent
Program rules:
- Don't execute program rules on events of other program stages (to discuss with @adrianq) -> required by the use case in the task
- Fix programStage/tei filter
- Add backup to run-program-rules
=> [program rules] Refinements

src/data/ImportTranslationsRepositorySpreadsheetRepository.ts, src/data/MetadataD2Repository.ts, src/data/dhis2-utils.ts, src/domain/entities/FieldTranslations.ts, src/domain/entities/MetadataObject.ts
Required by https://app.clickup.com/t/8693y7dbe
Make sure models are plural when necessary.
=> Sanitize models pluralization

src/data/ProgramEventsD2Repository.ts, src/data/d2-program-rules/D2ProgramRules.ts, src/data/dhis2-utils.ts, src/data/user-monitoring/common/UserMonitoringFileResourceUtils.ts
=> [fix] d2-api response type mismatch

README.md, package.json, src/data/CategoryOptionD2Repository.ts, src/data/ProgramEventsD2Repository.ts, src/data/TrackedEntityD2Repository.ts, src/data/UserD2Repository.ts, src/data/d2-program-rules/D2ProgramRules.ts, src/data/dhis2-utils.ts, src/data/user-monitoring/common/UserMonitoringFileResourceUtils.ts, src/data/user-monitoring/permission-fixer/PermissionFixerUserGroupD2Repository.ts, src/domain/entities/TrackedEntity.ts, src/domain/repositories/TrackedEntityRepository.ts, src/domain/usecases/TransferTrackedEntitiesUseCase.ts, src/scripts/cli.ts, src/scripts/commands/trackedEntities.ts, yarn.lock
Required by https://app.clickup.com/t/86952fqz0
=> [trackedEntities] Transfer TEIs (move to another orgUnit)

src/data/enrollments/EnrollmentsD2Repository.ts, src/data/enrollments/EventsD2Repository.ts, src/domain/entities/enrollments/Enrollment.ts, src/domain/entities/enrollments/Event.ts, src/domain/repositories/enrollments/EnrollmentsRepository.ts, src/domain/repositories/enrollments/EventsRepository.ts, src/domain/usecases/enrollments/CloseEnrollmentsUseCase.ts, src/scripts/cli.ts, src/scripts/commands/enrollments.ts, src/scripts/common.ts
Issue: [[1035] Update enrollment status - OpenMRS implementation](https://app.clickup.com/t/8696mcy0h)
This script will get the events for a given orgUnit and Program, get the associated active enrollments and close them.
=> Feat: Close active Enrollments based on its events updatedAt date

README.md, package.json, src/data/UsernameRenameSqlRepository.ts, src/data/sql/rename-usernames.sql, src/domain/entities/UsernameRename.ts, src/domain/repositories/UsernameRenameRepository.ts, src/domain/usecases/RenameUsernamesUseCase.ts, src/domain/usecases/user-monitoring/two-factor-monitoring/__tests__/TwoFactorTest.data.ts, src/scripts/commands/users.ts, yarn.lock
Required by: https://app.clickup.com/t/8696kv0dn
```shell
$ yarn start:dev users rename-username \
--mapping=user1old:user1new,user2old:user2new \
--dry-run --output=rename-ocba-dryrun.sql
$ docker exec -i DB_CONTAINER psql -U dhis dhis2 < rename-ocba-dryrun.sql
```
=> Rename usernames (SQL)

.github/workflows/codeql.yml
update codeql runner to use github runner
=> use gh runner

src/data/UsernameRenameSqlRepository.ts, src/declarations.d.ts, webpack.config.js
Fixes: https://app.clickup.com/t/8696km66q?comment=90120116408808
=> [fix] Add support for .sql import and use in UserRename
